### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by hardlynoticeable** [pixxelfactory/jInvertScroll#11]
On your website you say:
"WICH contain other elements,"

Have a good day;
Stephen.

**Comment by pixxelfactory** [comment]
Hi,
hahahaha, thanks for the advice, i corrected it!

Best regards
Alex
Pixxelfactory

Am 12.06.14 17:10, schrieb Stephen Akins:

**Comment by romdim** [comment]
Bump..
Great work though!

**Comment by hardlynoticeable** [comment]
np.  Have a great day.
