### ISSUE TITLE
How do I vertical align my content?

### ISSUE THREAD

**Issue by waisie** [pixxelfactory/jInvertScroll#24]
For example, in this example u showed us. 
http://codepen.io/SitePoint/pen/MKExrG

1. How do you vertical align middle the boxes? It doesn't matter if you resize your browser it will stay in the middle. 

2.Also for example if my browser with is 1200px, it will only show "jInvertScroll - A lightweight jQuery horizontal Parallax Plugin" box. So "jInvertScroll - A lightweight jQuery horizontal Parallax Plugin" AND "Quickstart" box will have a different background color. So if i'm viewing the " "jInvertScroll - A lightweight jQuery horizontal Parallax Plugin" box it will have a different background color.

**Comment by pixxelfactory** [comment]
Hi,

it works this way:
http://codepen.io/anon/pen/qqobPr

Essentially: the boxes are positioned absolute.
Set them to top: 50%;
and transform: translateY(-50%)

Best regards
Alex


Am 30.11.16 um 17:35 schrieb waisie:
