### ISSUE TITLE
how to implement it in wordpress

### ISSUE THREAD

**Issue by xJulex** [pixxelfactory/jInvertScroll#26]
Hello,
this is a very cool plugin and exactly what I need.

So I tried to implement it in wordpress, but I wasn't able to do this.
The problem is that I don't know very much about javascript.

Maybe, you can help me a little bit...

The first thing which I don't know is which files I should include to wordpress, because the plugin consists of different files in different folders.

And the next thing is the last step in your description...
(5.) In your javascript, use this code (the selectors refer to the elements that you desire to be scrolled) $.jInvertScroll(['yourselector1', 'yourselector2'...]);)

I don't know in which file I should write this line.
And is the selector a HTML element like section or div or is it a css class?

Thanks in advance!

**Comment by pixxelfactory** [comment]
Hi,
glad you like it, you need to include the jinvertscroll.css file and the .js file,
put them in your themes php-file (make sure that the .js-file is included after jquery).
Afterwards write the code inside a script-tag wich is placed after the js-includes..
For further questions about javascript and / or programming, please check out tutorials, jquery tutorials (http://try.jquery.com/) and stackoverflow.com.
