### ISSUE TITLE
How to change js file to scroll from right side to left?!

### ISSUE THREAD

**Issue by onrea** [pixxelfactory/jInvertScroll#7]
1. Is it possible to scroll from right to left side?
2. And is the below blue theme available for download anywhere?
   http://www.pixxelfactory.net/jInvertScroll/

**Comment by pixxelfactory** [comment]
Hi, first of all, please post only issues into the issue tracker,
post questions on stackoverflow if possible.

To your questions:

1.) in your css, replace "left: 0;" with: "right: 0;" on the layers, then, in the (non-minified-version) jInvertScoll js replace the last line: "el.el.css('left', pos);"  with "el.el.css('right', pos);"

2.) No, but feel free to take the css from that demo site if you wish, no problems about that.
