### ISSUE TITLE
Resize to work

### ISSUE THREAD

**Issue by lewhoff** [pixxelfactory/jInvertScroll#8]
I love the work you've don on this.  It is perfect for my project.

I have have one issue, every time the page is reloaded, the user has to resize the page (any amount) to get it to work.  Otherwise it will not scroll horizontally, only the items that do not have the class "scroll" will actually scroll.

This only happens when I upload it to my server.  When I check it on my local drive, it works just fine.

Here is what I'm working on so that you can see the problem.
http://watkinshoff.com/she-was-there/wwii/normandy.php

**Comment by pixxelfactory** [comment]
Hi,
thanks for your appreciation, about your project:
You need to cleanup your html-code, wich is quite messy,
a few tips:
1.) Specify a doctype (i recommend html5)
2.) <a href="..."><li>text</li></a> is wrong, <li><a href="...   is right  (a goes inside li, not vice-versa)
3.) Use http://validator.w3.org/  to validate your page and fix all errors
4.) You included jQuery two times, remove the 1.7 version

Best regards
Pixxelfactory

**Comment by lewhoff** [comment]
Thank you sooooo much!

On Wednesday, January 29, 2014 5:48 AM, pixxelfactory notifications@github.com wrote:

Hi,

**Comment by pixxelfactory** [comment]
You're welcome  =)

**Comment by lewhoff** [comment]
Thanks for all your help.  I fixed all the scripting issues and validated through http://validator.w3.org/.  But it still has the same problem, where the boxes of text (those divs without the "scroll" class)  will scroll, but the horizontal part (that with the class "scroll") will not scroll horizontally until the page is resized.

**Comment by pixxelfactory** [comment]
Hi,
remove the 1.7 version of jquery (second include) and it will work.
